import { Router, Request, Response } from 'express';
import { randomBytes } from 'crypto';
import QRCode from 'qrcode';
import { query, withSecurityContext } from '../db/postgres';
import { authMiddleware, AuthenticatedRequest } from '../middleware/auth';
import { verifyPassword, issueAccessToken, issueMfaChallenge, verifyMfaChallenge, hashRefreshToken, generateTotpSecret, verifyTotp, encryptMfaSecret, decryptMfaSecret, generateRecoveryCodes, hashRecoveryCode } from '../services/authService';

const router = Router();
const REFRESH_COOKIE = 'pngee_refresh';
function publicUser(row:any){return{id:row.id,organizationId:row.organization_id,name:row.name,email:row.email,role:row.role,avatarUrl:row.avatar_url||undefined,phone:row.phone||undefined,mfaEnabled:Boolean(row.mfa_enabled),status:row.status,lastLoginAt:row.last_login_at||undefined,lastLoginIp:row.last_login_ip||undefined,createdAt:row.created_at};}
function setRefreshCookie(res:Response,token:string){res.cookie(REFRESH_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/api/v1/auth',maxAge:Number(process.env.JWT_REFRESH_TTL_DAYS||30)*86400000});}
async function finishLogin(req:Request,res:Response,row:any){const accessToken=await issueAccessToken({sub:row.id,organizationId:row.organization_id,role:row.role});const refreshToken=randomBytes(48).toString('base64url');const expires=new Date(Date.now()+Number(process.env.JWT_REFRESH_TTL_DAYS||30)*86400000);await withSecurityContext(null,true,c=>c.query(`INSERT INTO refresh_tokens (id,user_id,token_hash,expires_at,created_ip,user_agent) VALUES ($1,$2,$3,$4,$5,$6)`,[randomBytes(16).toString('hex'),row.id,hashRefreshToken(refreshToken),expires.toISOString(),req.ip,req.get('user-agent')||null]));await withSecurityContext(null,true,c=>c.query('UPDATE users SET last_login_at=now(),last_login_ip=$2 WHERE id=$1',[row.id,req.ip]));setRefreshCookie(res,refreshToken);res.json({user:publicUser(row),accessToken});}

router.post('/login',async(req,res)=>{try{const{email,password}=req.body||{};if(typeof email!=='string'||typeof password!=='string')return res.status(400).json({error:'Email and password are required'});const r=await withSecurityContext(null,true,c=>c.query(`SELECT id,organization_id,name,email,role,avatar_url,phone,mfa_enabled,status,last_login_at,last_login_ip,created_at,password_hash FROM users WHERE lower(email)=lower($1) LIMIT 1`,[email.trim()]));const row=r.rows[0];if(!row||row.status!=='ACTIVE'||!row.password_hash||!(await verifyPassword(row.password_hash,password)))return res.status(401).json({error:'Invalid email or password'});if(row.mfa_enabled){return res.json({mfaRequired:true,mfaChallenge:await issueMfaChallenge(row.id),user:{id:row.id,email:row.email,mfaEnabled:true}});}await finishLogin(req,res,row);}catch(error){console.error('Login failed',error);res.status(500).json({error:'Authentication service unavailable'});}});

router.post('/mfa/verify',async(req,res)=>{try{const{mfaChallenge,code,recoveryCode}=req.body||{};if(typeof mfaChallenge!=='string'||(typeof code!=='string'&&typeof recoveryCode!=='string'))return res.status(400).json({error:'MFA challenge and code are required'});const userId=await verifyMfaChallenge(mfaChallenge);const r=await withSecurityContext(null,true,c=>c.query(`SELECT id,organization_id,name,email,role,avatar_url,phone,mfa_enabled,status,last_login_at,last_login_ip,created_at,mfa_secret_enc,mfa_recovery_hashes FROM users WHERE id=$1 AND status='ACTIVE'`,[userId]));const row=r.rows[0];if(!row||!row.mfa_enabled||!row.mfa_secret_enc)return res.status(401).json({error:'Invalid MFA challenge'});let valid=false;let usedRecoveryHash:string|undefined;if(typeof code==='string')valid=verifyTotp(decryptMfaSecret(row.mfa_secret_enc),code.trim());if(!valid&&typeof recoveryCode==='string'){const hash=hashRecoveryCode(recoveryCode);const hashes=Array.isArray(row.mfa_recovery_hashes)?row.mfa_recovery_hashes:[];if(hashes.includes(hash)){valid=true;usedRecoveryHash=hash;await withSecurityContext(null,true,c=>c.query(`UPDATE users SET mfa_recovery_hashes = COALESCE(mfa_recovery_hashes,'[]'::jsonb) - $2::text WHERE id=$1`,[row.id,hash]));}}if(!valid)return res.status(401).json({error:'Invalid MFA code'});if(usedRecoveryHash)console.warn(`Recovery code consumed for user ${row.id}`);await finishLogin(req,res,row);}catch{res.status(401).json({error:'Invalid or expired MFA challenge'});}});

router.post('/mfa/setup',authMiddleware as any,async(req:AuthenticatedRequest,res)=>{try{const secret=generateTotpSecret();const issuer=process.env.MFA_ISSUER||'PNGee CyberGuard';const label=encodeURIComponent(`${issuer}:${req.user!.email}`);const otpauth=`otpauth://totp/${label}?secret=${secret}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`;const qrCodeDataUrl=await QRCode.toDataURL(otpauth);res.json({secret,otpauthUrl:otpauth,qrCodeDataUrl});}catch{res.status(500).json({error:'Unable to initialize MFA setup'});}});
router.post('/mfa/enable',authMiddleware as any,async(req:AuthenticatedRequest,res)=>{try{const{secret,code}=req.body||{};if(typeof secret!=='string'||typeof code!=='string'||!verifyTotp(secret,code))return res.status(400).json({error:'Invalid MFA secret or verification code'});const recoveryCodes=generateRecoveryCodes();await withSecurityContext(req.user!.organizationId,false,c=>c.query(`UPDATE users SET mfa_enabled=true,mfa_secret_enc=$2,mfa_recovery_hashes=$3,mfa_enrolled_at=now() WHERE id=$1`,[req.user!.id,encryptMfaSecret(secret),JSON.stringify(recoveryCodes.map(hashRecoveryCode))]));res.json({enabled:true,recoveryCodes});}catch{res.status(500).json({error:'Unable to enable MFA'});}});
router.post('/mfa/disable',authMiddleware as any,async(req:AuthenticatedRequest,res)=>{try{const{code}=req.body||{};if(typeof code!=='string')return res.status(400).json({error:'Current MFA code is required'});const r=await withSecurityContext(req.user!.organizationId,false,c=>c.query(`SELECT mfa_enabled,mfa_secret_enc FROM users WHERE id=$1`,[req.user!.id]));const row=r.rows[0];if(!row?.mfa_enabled||!row.mfa_secret_enc||!verifyTotp(decryptMfaSecret(row.mfa_secret_enc),code))return res.status(401).json({error:'Invalid MFA code'});await withSecurityContext(req.user!.organizationId,false,c=>c.query(`UPDATE users SET mfa_enabled=false,mfa_secret_enc=NULL,mfa_recovery_hashes='[]'::jsonb,mfa_enrolled_at=NULL WHERE id=$1`,[req.user!.id]));res.json({enabled:false});}catch{res.status(500).json({error:'Unable to disable MFA'});}});

router.post('/refresh',async(req,res)=>{try{const token=req.cookies?.[REFRESH_COOKIE];if(!token)return res.status(401).json({error:'Refresh token required'});const r=await withSecurityContext(null,true,c=>c.query(`SELECT rt.id refresh_id,rt.user_id,u.organization_id,u.name,u.email,u.role,u.avatar_url,u.phone,u.mfa_enabled,u.status,u.last_login_at,u.last_login_ip,u.created_at FROM refresh_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=$1 AND rt.revoked_at IS NULL AND rt.expires_at>now() LIMIT 1`,[hashRefreshToken(token)]));const row=r.rows[0];if(!row||row.status!=='ACTIVE'){res.clearCookie(REFRESH_COOKIE,{path:'/api/v1/auth'});return res.status(401).json({error:'Invalid or expired refresh token'});}const nextRefresh=randomBytes(48).toString('base64url'),nextId=randomBytes(16).toString('hex');await withSecurityContext(null,true,async c=>{await c.query('UPDATE refresh_tokens SET revoked_at=now(),replaced_by=$2 WHERE id=$1',[row.refresh_id,nextId]);await c.query(`INSERT INTO refresh_tokens (id,user_id,token_hash,expires_at,created_ip,user_agent) VALUES ($1,$2,$3,$4,$5,$6)`,[nextId,row.user_id,hashRefreshToken(nextRefresh),new Date(Date.now()+Number(process.env.JWT_REFRESH_TTL_DAYS||30)*86400000).toISOString(),req.ip,req.get('user-agent')||null]);});setRefreshCookie(res,nextRefresh);res.json({user:publicUser(row),accessToken:await issueAccessToken({sub:row.user_id,organizationId:row.organization_id,role:row.role})});}catch{res.status(500).json({error:'Authentication service unavailable'});}});
router.post('/logout',async(req,res)=>{const token=req.cookies?.[REFRESH_COOKIE];if(token)await query('UPDATE refresh_tokens SET revoked_at=now() WHERE token_hash=$1',[hashRefreshToken(token)]);res.clearCookie(REFRESH_COOKIE,{path:'/api/v1/auth'});res.status(204).send();});
router.get('/me',authMiddleware as any,async(req:AuthenticatedRequest,res)=>{const r=await withSecurityContext(req.user!.organizationId,Boolean(req.user&&['PNGEE_SUPER_ADMIN','PNGEE_SECURITY_ANALYST','STK_SUPER_ADMIN','STK_SECURITY_ANALYST'].includes(req.user.role)),c=>c.query('SELECT * FROM organizations WHERE id=$1',[req.user!.organizationId]));res.json({user:req.user,organization:r.rows[0]||null,availableOrgs:[]});});
export default router;
