import { 
  Organization, 
  User, 
  Asset, 
  SecurityEvent, 
  DetectionRule, 
  SecurityAlert, 
  SecurityIncident, 
  Vulnerability, 
  SslCertificate, 
  MonitoredDomain, 
  BackupRecord, 
  ExternalExposureRecord, 
  IdentityAuthStat, 
  AuditLog, 
  NotificationRule, 
  ThreatIntelligenceIndicator, 
  IntegrationConnector,
  SubscriptionPlanDetails,
  AgentEnrollmentToken,
  SecurityReport
} from '../../src/types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-pngee-global',
    name: 'PNGee IT Solutions (Global SOC & Operations)',
    slug: 'pngee-ops',
    domain: 'pngeecyberguard.com',
    contactEmail: 'soc@pngeecyberguard.com',
    contactPhone: '+1 (800) 555-PNGEE',
    address: '100 Cyber Defense Way, Suite 400, Austin, TX',
    plan: 'PNGEE_ENTERPRISE',
    status: 'ACTIVE',
    maxAssets: 10000,
    assignedAnalysts: ['usr-pngee-analyst-1', 'usr-pngee-admin-1'],
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'org-apex-logistics',
    name: 'Apex Global Logistics Inc.',
    slug: 'apex-logistics',
    domain: 'apexlogistics.com',
    contactEmail: 'it-security@apexlogistics.com',
    contactPhone: '+1 (312) 555-0199',
    address: '450 Harbor Boulevard, Chicago, IL',
    plan: 'PNGEE_ENTERPRISE',
    status: 'ACTIVE',
    maxAssets: 150,
    assignedAnalysts: ['usr-pngee-analyst-1'],
    createdAt: '2025-03-10T09:30:00Z',
    updatedAt: '2026-08-15T14:20:00Z',
  },
  {
    id: 'org-nexus-health',
    name: 'Nexus Healthcare Systems LLC',
    slug: 'nexus-health',
    domain: 'nexushealth.org',
    contactEmail: 'compliance@nexushealth.org',
    contactPhone: '+1 (617) 555-8821',
    address: '77 Medical Plaza, Boston, MA',
    plan: 'PNGEE_BUSINESS',
    status: 'ACTIVE',
    maxAssets: 75,
    assignedAnalysts: ['usr-pngee-analyst-1'],
    createdAt: '2025-05-20T11:00:00Z',
    updatedAt: '2026-08-20T16:45:00Z',
  },
  {
    id: 'org-vanguard-fin',
    name: 'Vanguard Capital Advisory',
    slug: 'vanguard-fin',
    domain: 'vanguardfin.com',
    contactEmail: 'ciso@vanguardfin.com',
    contactPhone: '+1 (212) 555-4300',
    address: '1 Wall Street Court, New York, NY',
    plan: 'PNGEE_ENTERPRISE',
    status: 'ACTIVE',
    maxAssets: 200,
    assignedAnalysts: ['usr-pngee-analyst-1'],
    createdAt: '2025-02-01T10:15:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-pngee-admin-1',
    organizationId: 'org-pngee-global',
    name: 'Marcus Vance (PNGee Lead)',
    email: 'admin@pngeecyberguard.com',
    role: 'PNGEE_SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '+1 (512) 555-0101',
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-01T21:45:00Z',
    lastLoginIp: '198.51.100.4',
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'usr-pngee-analyst-1',
    organizationId: 'org-pngee-global',
    name: 'Elena Rostova (PNGee SOC Analyst)',
    email: 'analyst@pngeecyberguard.com',
    role: 'PNGEE_SECURITY_ANALYST',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    phone: '+1 (512) 555-0102',
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-01T22:10:00Z',
    lastLoginIp: '198.51.100.12',
    createdAt: '2025-01-20T09:00:00Z',
  },
  {
    id: 'usr-apex-admin',
    organizationId: 'org-apex-logistics',
    name: 'David Sterling',
    email: 'admin@apexlogistics.com',
    role: 'CUSTOMER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+1 (312) 555-0199',
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-01T18:30:00Z',
    lastLoginIp: '203.0.113.88',
    createdAt: '2025-03-10T10:00:00Z',
  },
  {
    id: 'usr-apex-user',
    organizationId: 'org-apex-logistics',
    name: 'Sarah Chen (IT Support)',
    email: 'read-only@apexlogistics.com',
    role: 'CUSTOMER_USER',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    phone: '+1 (312) 555-0188',
    mfaEnabled: false,
    status: 'ACTIVE',
    lastLoginAt: '2026-08-30T14:15:00Z',
    lastLoginIp: '203.0.113.91',
    createdAt: '2025-04-01T11:00:00Z',
  },
  {
    id: 'usr-nexus-admin',
    organizationId: 'org-nexus-health',
    name: 'Dr. Rachel Adams',
    email: 'admin@nexushealth.org',
    role: 'CUSTOMER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    phone: '+1 (617) 555-8822',
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-01T15:00:00Z',
    lastLoginIp: '198.18.0.42',
    createdAt: '2025-05-20T12:00:00Z',
  },
  {
    id: 'usr-vanguard-admin',
    organizationId: 'org-vanguard-fin',
    name: 'Alexander Sterling',
    email: 'security@vanguardfin.com',
    role: 'CUSTOMER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+1 (212) 555-4301',
    mfaEnabled: true,
    status: 'ACTIVE',
    lastLoginAt: '2026-09-01T20:10:00Z',
    lastLoginIp: '198.51.100.99',
    createdAt: '2025-02-01T11:00:00Z',
  }
];

export const INITIAL_PLANS: SubscriptionPlanDetails[] = [
  {
    planId: 'PNGEE_BASIC',
    name: 'PNGee CyberGuard Basic',
    description: 'Essential monitoring & security visibility for small teams.',
    priceMonthlyUSD: 499,
    maxAssets: 25,
    features: {
      endpointMonitoring: true,
      vulnerabilityManagement: false,
      incidentResponse: false,
      sslDomainMonitoring: true,
      backupMonitoring: true,
      externalExposure: false,
      aiSecurityCopilot: false,
      dedicatedAnalyst: false,
      slaHours: 24,
      customIntegrations: false,
    }
  },
  {
    planId: 'PNGEE_BUSINESS',
    name: 'PNGee CyberGuard Business',
    description: 'Full endpoint, vulnerability, firewall and exposure protection for growing SMBs.',
    priceMonthlyUSD: 1499,
    maxAssets: 100,
    features: {
      endpointMonitoring: true,
      vulnerabilityManagement: true,
      incidentResponse: true,
      sslDomainMonitoring: true,
      backupMonitoring: true,
      externalExposure: true,
      aiSecurityCopilot: true,
      dedicatedAnalyst: false,
      slaHours: 4,
      customIntegrations: false,
    }
  },
  {
    planId: 'PNGEE_ENTERPRISE',
    name: 'PNGee CyberGuard Enterprise SOC',
    description: 'Comprehensive 24/7 Managed SOC, threat intelligence, custom integrations & SLA guarantees.',
    priceMonthlyUSD: 3999,
    maxAssets: 500,
    features: {
      endpointMonitoring: true,
      vulnerabilityManagement: true,
      incidentResponse: true,
      sslDomainMonitoring: true,
      backupMonitoring: true,
      externalExposure: true,
      aiSecurityCopilot: true,
      dedicatedAnalyst: true,
      slaHours: 1,
      customIntegrations: true,
    }
  }
];

export const INITIAL_DETECTION_RULES: DetectionRule[] = [
  {
    id: 'rule-brute-force',
    name: 'Excessive Failed Authentication Attempts (Brute-Force)',
    description: 'Detects more than 5 failed login attempts for a single account within 5 minutes.',
    severity: 'HIGH',
    category: 'Authentication',
    enabled: true,
    threshold: 5,
    timeWindowMinutes: 5,
    mitreTechnique: 'T1110 (Brute Force)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'count(events.failed_login) >= 5 per target_user within 300s',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'rule-impossible-travel',
    name: 'Impossible Travel / Anomalous Geolocation',
    description: 'Triggers when identical credentials authenticate from disparate countries within 1 hour.',
    severity: 'CRITICAL',
    category: 'Identity',
    enabled: true,
    threshold: 2,
    timeWindowMinutes: 60,
    mitreTechnique: 'T1078 (Valid Accounts)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'geo_distance(login1, login2) > 1500km and time_delta < 3600s',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'rule-privilege-escalation',
    name: 'Unauthorized Domain Administrator Account Created',
    description: 'Identifies new administrative group memberships or elevated privileges granted.',
    severity: 'CRITICAL',
    category: 'Identity',
    enabled: true,
    threshold: 1,
    timeWindowMinutes: 10,
    mitreTechnique: 'T1068 (Privilege Escalation)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'event.type == "member_added_to_privileged_group" and actor != "approved_change_bot"',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'rule-malware-quarantine',
    name: 'Endpoint Malware Execution / Quarantine Trigger',
    description: 'EDR agent reports execution of malicious binary or signature match.',
    severity: 'CRITICAL',
    category: 'Malware',
    enabled: true,
    threshold: 1,
    timeWindowMinutes: 5,
    mitreTechnique: 'T1204 (User Execution - Malicious File)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'agent.edr_alert.type == "malware_blocked" or "malware_detected"',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
  },
  {
    id: 'rule-suspicious-powershell',
    name: 'Obfuscated PowerShell / Encoded Command Execution',
    description: 'Identifies execution of base64 encoded PowerShell or bypass invocation.',
    severity: 'HIGH',
    category: 'Endpoint',
    enabled: true,
    threshold: 1,
    timeWindowMinutes: 10,
    mitreTechnique: 'T1059.001 (Command & Scripting Interpreter: PowerShell)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'process.name == "powershell.exe" and process.command_line contains "-enc" or "-bypass"',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-04-05T00:00:00Z',
  },
  {
    id: 'rule-firewall-port-scan',
    name: 'External Inbound Reconnaissance & Port Scanning',
    description: 'Perimeter firewall detects single external IP probing >30 distinct ports in 2 minutes.',
    severity: 'MEDIUM',
    category: 'Network',
    enabled: true,
    threshold: 30,
    timeWindowMinutes: 2,
    mitreTechnique: 'T1046 (Network Service Discovery)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'BATCHED',
    conditionLogic: 'distinct_count(destination_port) > 30 per source_ip within 120s',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },
  {
    id: 'rule-av-disabled',
    name: 'Endpoint Antivirus / EDR Agent Tampered or Disabled',
    description: 'Agent telemetry indicates real-time protection or firewall service stopped unexpectedly.',
    severity: 'HIGH',
    category: 'Endpoint',
    enabled: true,
    threshold: 1,
    timeWindowMinutes: 5,
    mitreTechnique: 'T1562.001 (Impair Defenses: Disable Tools)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'telemetry.antivirus_enabled == false or telemetry.firewall_enabled == false',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-05-20T00:00:00Z',
  },
  {
    id: 'rule-cert-expiry-critical',
    name: 'SSL/TLS Certificate Expiration Imminent (< 7 Days)',
    description: 'Monitored customer web certificate will expire in under 7 days without renewal.',
    severity: 'HIGH',
    category: 'Policy violation',
    enabled: true,
    threshold: 1,
    timeWindowMinutes: 1440,
    mitreTechnique: 'T1588 (Obtain Capabilities)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'certificate.days_remaining <= 7 and certificate.status != "VALID"',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'rule-backup-failure',
    name: 'Critical System Backup Failure (RPO Breached)',
    description: 'Backup system reports failure or missed scheduled snapshot on critical asset.',
    severity: 'HIGH',
    category: 'Data security',
    enabled: true,
    threshold: 1,
    timeWindowMinutes: 720,
    mitreTechnique: 'T1490 (Inhibit System Recovery)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'backup.status == "FAILED" or backup.backup_age_hours > 36',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 'rule-suspicious-dns-tunneling',
    name: 'High-Volume DNS Query Anomaly / Suspected Data Exfiltration',
    description: 'High entropy domain queries and anomalous TXT record length detected.',
    severity: 'HIGH',
    category: 'DNS',
    enabled: true,
    threshold: 50,
    timeWindowMinutes: 5,
    mitreTechnique: 'T1071.004 (Application Layer Protocol: DNS)',
    organizationScope: 'GLOBAL',
    notificationPolicy: 'IMMEDIATE',
    conditionLogic: 'dns.query_entropy > 4.2 and count(dns.txt_requests) > 50 in 300s',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  }
];

export const INITIAL_ASSETS: Asset[] = [
  // Apex Logistics Assets
  {
    id: 'ast-apex-01',
    organizationId: 'org-apex-logistics',
    hostname: 'APEX-DC01-WIN',
    ipAddress: '10.100.1.5',
    macAddress: '00:50:56:A1:B2:C3',
    operatingSystem: 'Windows Server',
    osVersion: '2022 Datacenter (21H2)',
    manufacturer: 'Dell',
    model: 'PowerEdge R750',
    serialNumber: 'SRV-DL-88231',
    owner: 'IT Operations',
    location: 'Chicago HQ - Data Hall 1',
    assetType: 'Server',
    criticality: 'CRITICAL',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:38:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.1',
    securityStatus: 'SECURE',
    tags: ['ActiveDirectory', 'DomainController', 'Tier0', 'DNS'],
    notes: 'Primary active directory domain controller. Requires high-priority monitoring.',
    telemetry: {
      cpuUsagePercent: 24,
      ramUsagePercent: 62,
      diskUsagePercent: 41,
      antivirusEnabled: true,
      antivirusUpToDate: true,
      firewallEnabled: true,
      missingPatchesCount: 0,
      runningProcessesCount: 142,
      loggedInUsers: ['svc_ad_sync', 'dsterling_admin']
    },
    createdAt: '2025-03-10T10:00:00Z',
    updatedAt: '2026-09-01T22:38:00Z'
  },
  {
    id: 'ast-apex-02',
    organizationId: 'org-apex-logistics',
    hostname: 'APEX-FW01-FORTIGATE',
    ipAddress: '198.51.100.254',
    macAddress: '70:4C:A5:11:22:33',
    operatingSystem: 'FortiOS',
    osVersion: '7.4.3 build2573',
    manufacturer: 'Fortinet',
    model: 'FortiGate 100F',
    serialNumber: 'FG100FTK2300918',
    owner: 'Network Security',
    location: 'Chicago HQ - Perimeter Rack',
    assetType: 'Firewall',
    criticality: 'CRITICAL',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:40:00Z',
    agentStatus: 'NOT_INSTALLED',
    securityStatus: 'AT_RISK',
    tags: ['Perimeter', 'VPN', 'Fortinet', 'IPS_Enabled'],
    notes: 'Perimeter gateway firewall. Fortinet SSL-VPN patch CVE-2024-21762 pending verification.',
    createdAt: '2025-03-10T10:30:00Z',
    updatedAt: '2026-09-01T22:40:00Z'
  },
  {
    id: 'ast-apex-03',
    organizationId: 'org-apex-logistics',
    hostname: 'APEX-APP01-LNX',
    ipAddress: '10.100.2.14',
    macAddress: '52:54:00:88:99:AA',
    operatingSystem: 'Ubuntu Linux',
    osVersion: '22.04.4 LTS',
    manufacturer: 'VMware Virtual Platform',
    model: 'ESXi VM',
    serialNumber: 'VMware-42 1a 88 12',
    owner: 'DevOps & Logistics Team',
    location: 'Chicago HQ - Cluster A',
    assetType: 'Linux Endpoint',
    criticality: 'HIGH',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:35:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.1',
    securityStatus: 'SECURE',
    tags: ['ContainerHost', 'Docker', 'DispatchSystem'],
    telemetry: {
      cpuUsagePercent: 48,
      ramUsagePercent: 78,
      diskUsagePercent: 65,
      antivirusEnabled: true,
      antivirusUpToDate: true,
      firewallEnabled: true,
      missingPatchesCount: 2,
      runningProcessesCount: 89,
      loggedInUsers: ['deploy_bot']
    },
    createdAt: '2025-03-12T14:00:00Z',
    updatedAt: '2026-09-01T22:35:00Z'
  },
  {
    id: 'ast-apex-04',
    organizationId: 'org-apex-logistics',
    hostname: 'APEX-FIN-LT08',
    ipAddress: '10.100.5.122',
    macAddress: 'F0:18:98:C4:D5:E6',
    operatingSystem: 'Windows 11 Pro',
    osVersion: '23H2 (22631.3296)',
    manufacturer: 'Lenovo',
    model: 'ThinkPad X1 Carbon Gen 11',
    serialNumber: 'PF-49X8L2',
    owner: 'Finance Manager (D. Sterling)',
    location: 'Executive Suite / Remote',
    assetType: 'Windows Endpoint',
    criticality: 'HIGH',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:20:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.1',
    securityStatus: 'AT_RISK',
    tags: ['Finance', 'Executive', 'BitLocker_Active'],
    notes: 'Detected repeated failed VPN authentications and unusual after-hours network connection.',
    telemetry: {
      cpuUsagePercent: 12,
      ramUsagePercent: 54,
      diskUsagePercent: 33,
      antivirusEnabled: true,
      antivirusUpToDate: true,
      firewallEnabled: true,
      missingPatchesCount: 1,
      runningProcessesCount: 180,
      loggedInUsers: ['dsterling']
    },
    createdAt: '2025-04-05T09:00:00Z',
    updatedAt: '2026-09-01T22:20:00Z'
  },
  {
    id: 'ast-apex-05',
    organizationId: 'org-apex-logistics',
    hostname: 'APEX-WH-PRINTER01',
    ipAddress: '10.100.8.44',
    macAddress: '00:1E:8F:77:66:55',
    operatingSystem: 'Embedded Linux',
    osVersion: 'Zebra OS v4.1',
    manufacturer: 'Zebra',
    model: 'ZT411 Thermal Printer',
    serialNumber: 'ZBR-9912001',
    owner: 'Warehouse Ops',
    location: 'Dock 4 Logistics Bay',
    assetType: 'Printer',
    criticality: 'LOW',
    status: 'ONLINE',
    lastSeen: '2026-09-01T21:00:00Z',
    agentStatus: 'NOT_INSTALLED',
    securityStatus: 'SECURE',
    tags: ['IoT', 'Warehouse', 'OT'],
    createdAt: '2025-04-10T12:00:00Z',
    updatedAt: '2026-09-01T21:00:00Z'
  },

  // Nexus Health Assets
  {
    id: 'ast-nexus-01',
    organizationId: 'org-nexus-health',
    hostname: 'NEXUS-EHR-DB01',
    ipAddress: '10.200.1.10',
    macAddress: '00:50:56:B9:AA:11',
    operatingSystem: 'Red Hat Enterprise Linux',
    osVersion: '9.3 (Plow)',
    manufacturer: 'HPE',
    model: 'ProLiant DL380 Gen10',
    serialNumber: 'HP-USE91024L',
    owner: 'Clinical Informatics',
    location: 'Boston Medical Data Facility',
    assetType: 'Server',
    criticality: 'CRITICAL',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:30:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.1',
    securityStatus: 'SECURE',
    tags: ['HIPAA', 'EHR', 'PostgreSQL', 'EncryptedAtRest'],
    notes: 'Patient Electronic Health Records Database. Strict audit log retention mandatory.',
    telemetry: {
      cpuUsagePercent: 35,
      ramUsagePercent: 82,
      diskUsagePercent: 58,
      antivirusEnabled: true,
      antivirusUpToDate: true,
      firewallEnabled: true,
      missingPatchesCount: 0,
      runningProcessesCount: 110,
      loggedInUsers: ['svc_ehr_app']
    },
    createdAt: '2025-05-20T12:00:00Z',
    updatedAt: '2026-09-01T22:30:00Z'
  },
  {
    id: 'ast-nexus-02',
    organizationId: 'org-nexus-health',
    hostname: 'NEXUS-CLINIC-WS12',
    ipAddress: '10.200.4.55',
    macAddress: '3C:52:82:11:44:77',
    operatingSystem: 'Windows 11 Enterprise',
    osVersion: '23H2',
    manufacturer: 'Dell',
    model: 'OptiPlex 7000 Micro',
    serialNumber: 'DL-7X9811',
    owner: 'Clinic Floor Station 3',
    location: 'Outpatient Care Clinic A',
    assetType: 'Windows Endpoint',
    criticality: 'MEDIUM',
    status: 'DEGRADED',
    lastSeen: '2026-09-01T20:15:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.0',
    securityStatus: 'AT_RISK',
    tags: ['NurseStation', 'CardReader', 'HIPAA'],
    notes: 'Real-time protection reported 3 missing security patches and delayed heartbeat.',
    telemetry: {
      cpuUsagePercent: 65,
      ramUsagePercent: 71,
      diskUsagePercent: 89,
      antivirusEnabled: true,
      antivirusUpToDate: false,
      firewallEnabled: true,
      missingPatchesCount: 3,
      runningProcessesCount: 165,
      loggedInUsers: ['rn_station3']
    },
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2026-09-01T20:15:00Z'
  },
  {
    id: 'ast-nexus-03',
    organizationId: 'org-nexus-health',
    hostname: 'NEXUS-EDGE-PFSENSE',
    ipAddress: '198.18.0.1',
    macAddress: 'A0:36:9F:55:66:77',
    operatingSystem: 'FreeBSD',
    osVersion: 'pfSense Plus 23.09.1',
    manufacturer: 'Netgate',
    model: '6100 Max',
    serialNumber: 'NG6100-8812',
    owner: 'Network Infrastructure',
    location: 'Boston Datacenter Room 104',
    assetType: 'Firewall',
    criticality: 'CRITICAL',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:42:00Z',
    agentStatus: 'NOT_INSTALLED',
    securityStatus: 'SECURE',
    tags: ['Perimeter', 'pfSense', 'Suricata_IPS', 'HIPAA_VPN'],
    createdAt: '2025-05-22T14:00:00Z',
    updatedAt: '2026-09-01T22:42:00Z'
  },

  // Vanguard Financial Assets
  {
    id: 'ast-van-01',
    organizationId: 'org-vanguard-fin',
    hostname: 'VAN-TRADE-PROD01',
    ipAddress: '10.50.1.20',
    macAddress: '00:15:5D:77:88:99',
    operatingSystem: 'Windows Server',
    osVersion: '2025 Preview / 2022 Datacenter',
    manufacturer: 'Cisco UCS',
    model: 'B200 M6 Blade',
    serialNumber: 'FCH241108K',
    owner: 'Trading Operations',
    location: 'NY4 Equinix Secaucus Datacenter',
    assetType: 'Server',
    criticality: 'CRITICAL',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:41:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.1',
    securityStatus: 'SECURE',
    tags: ['PCI_DSS', 'TradingCore', 'LowLatency', 'Tier0'],
    telemetry: {
      cpuUsagePercent: 55,
      ramUsagePercent: 88,
      diskUsagePercent: 42,
      antivirusEnabled: true,
      antivirusUpToDate: true,
      firewallEnabled: true,
      missingPatchesCount: 0,
      runningProcessesCount: 210,
      loggedInUsers: ['svc_quant_engine']
    },
    createdAt: '2025-02-01T11:00:00Z',
    updatedAt: '2026-09-01T22:41:00Z'
  },
  {
    id: 'ast-van-02',
    organizationId: 'org-vanguard-fin',
    hostname: 'VAN-CISO-MBP16',
    ipAddress: '10.50.10.84',
    macAddress: 'F4:D4:88:22:33:44',
    operatingSystem: 'macOS Sonoma',
    osVersion: '14.4.1 (23E224)',
    manufacturer: 'Apple',
    model: 'MacBook Pro 16-inch M3 Max',
    serialNumber: 'C02G8901MD6R',
    owner: 'CISO (A. Sterling)',
    location: 'NYC Office / Executive',
    assetType: 'macOS Endpoint',
    criticality: 'HIGH',
    status: 'ONLINE',
    lastSeen: '2026-09-01T22:30:00Z',
    agentStatus: 'ACTIVE',
    agentVersion: 'v2.4.1',
    securityStatus: 'SECURE',
    tags: ['Executive', 'FileVault_Active', 'CISO'],
    telemetry: {
      cpuUsagePercent: 18,
      ramUsagePercent: 45,
      diskUsagePercent: 28,
      antivirusEnabled: true,
      antivirusUpToDate: true,
      firewallEnabled: true,
      missingPatchesCount: 0,
      runningProcessesCount: 240,
      loggedInUsers: ['asterling']
    },
    createdAt: '2025-02-15T09:00:00Z',
    updatedAt: '2026-09-01T22:30:00Z'
  }
];

export const INITIAL_SECURITY_EVENTS: SecurityEvent[] = [
  {
    id: 'evt-8901',
    organizationId: 'org-apex-logistics',
    timestamp: '2026-09-01T22:14:22Z',
    source: 'APEX-FW01-FORTIGATE',
    sourceType: 'FIREWALL',
    severity: 'CRITICAL',
    eventCategory: 'Authentication',
    sourceIP: '185.220.101.44',
    destinationIP: '198.51.100.254',
    username: 'admin',
    host: 'APEX-FW01-FORTIGATE',
    device: 'FortiGate 100F',
    eventDescription: 'Repeated SSL-VPN credential stuffing failure: 14 failed logins in 45 seconds from Tor exit node.',
    rawEventReference: 'fg_log_id=0100032001 type="vpn" subtype="ssl" action="auth-failure" user="admin" srcip="185.220.101.44" reason="credential_invalid"',
    detectionRuleId: 'rule-brute-force',
    mitreTechnique: 'T1110.003 (Password Spraying)',
    status: 'CORRELATED',
    analystNotes: 'Associated with Alert ALT-1049. IP added to temporary perimeter drop list.',
    createdTimestamp: '2026-09-01T22:14:25Z'
  },
  {
    id: 'evt-8902',
    organizationId: 'org-apex-logistics',
    timestamp: '2026-09-01T22:15:10Z',
    source: 'APEX-FIN-LT08',
    sourceType: 'ENDPOINT_AGENT',
    severity: 'HIGH',
    eventCategory: 'Identity',
    sourceIP: '45.154.255.90',
    destinationIP: '10.100.5.122',
    username: 'dsterling',
    host: 'APEX-FIN-LT08',
    device: 'ThinkPad X1 Carbon',
    eventDescription: 'Microsoft 365 login token generated from Sofia, Bulgaria within 22 minutes of Chicago login.',
    rawEventReference: 'm365_sign_in_id=22a9f1-002 user="dsterling@apexlogistics.com" country="BG" city="Sofia" clientApp="ExchangeActiveSync" riskLevel="high"',
    detectionRuleId: 'rule-impossible-travel',
    mitreTechnique: 'T1078 (Valid Accounts)',
    status: 'CORRELATED',
    analystNotes: 'Suspicious impossible travel event confirmed. Session revoked and MFA prompt forced.',
    createdTimestamp: '2026-09-01T22:15:15Z'
  },
  {
    id: 'evt-8903',
    organizationId: 'org-apex-logistics',
    timestamp: '2026-09-01T21:48:00Z',
    source: 'APEX-DC01-WIN',
    sourceType: 'ENDPOINT_AGENT',
    severity: 'MEDIUM',
    eventCategory: 'Endpoint',
    sourceIP: '10.100.2.14',
    destinationIP: '10.100.1.5',
    username: 'deploy_bot',
    host: 'APEX-DC01-WIN',
    device: 'PowerEdge R750',
    eventDescription: 'Kerberos service ticket requested with RC4 cipher suite (Potential Kerberoasting activity).',
    rawEventReference: 'win_evt_id=4769 ServiceName="MSSQLSvc/db01.apex.local" TicketEncryptionType="0x17" ClientAddress="10.100.2.14"',
    detectionRuleId: 'rule-suspicious-powershell',
    mitreTechnique: 'T1558.003 (Steal or Forge Kerberos Tickets: Kerberoasting)',
    status: 'PROCESSED',
    createdTimestamp: '2026-09-01T21:48:05Z'
  },
  {
    id: 'evt-8904',
    organizationId: 'org-nexus-health',
    timestamp: '2026-09-01T20:30:18Z',
    source: 'NEXUS-EDGE-PFSENSE',
    sourceType: 'FIREWALL',
    severity: 'MEDIUM',
    eventCategory: 'Network',
    sourceIP: '91.240.118.172',
    destinationIP: '198.18.0.1',
    host: 'NEXUS-EDGE-PFSENSE',
    device: 'Netgate 6100',
    eventDescription: 'Suricata IPS triggered: Inbound TCP SYN scan sweep on healthcare API listener port 8443.',
    rawEventReference: 'suricata[8820]: [1:2001219:19] ET SCAN Potential SSH/HTTPS Scan [Classification: Attempted Information Leak] [Priority: 2] {TCP} 91.240.118.172 -> 198.18.0.1:8443',
    detectionRuleId: 'rule-firewall-port-scan',
    mitreTechnique: 'T1046 (Network Service Discovery)',
    status: 'PROCESSED',
    createdTimestamp: '2026-09-01T20:30:22Z'
  },
  {
    id: 'evt-8905',
    organizationId: 'org-nexus-health',
    timestamp: '2026-09-01T19:10:00Z',
    source: 'NEXUS-CLINIC-WS12',
    sourceType: 'ENDPOINT_AGENT',
    severity: 'HIGH',
    eventCategory: 'Malware',
    sourceIP: '10.200.4.55',
    username: 'rn_station3',
    host: 'NEXUS-CLINIC-WS12',
    device: 'OptiPlex 7000 Micro',
    eventDescription: 'Windows Defender quarantined suspicious macro attachment: Trojan:O97M/Qakbot.gen!pz in temp directory.',
    rawEventReference: 'mp_log=1116 path="C:\\Users\\rn_station3\\AppData\\Local\\Temp\\invoice_doc_771.vbs" threat="Trojan:O97M/Qakbot.gen!pz" action="quarantine" status="success"',
    detectionRuleId: 'rule-malware-quarantine',
    mitreTechnique: 'T1204.002 (Malicious File)',
    status: 'CORRELATED',
    analystNotes: 'Quarantined successfully. Endpoint memory scan initiated.',
    createdTimestamp: '2026-09-01T19:10:05Z'
  },
  {
    id: 'evt-8906',
    organizationId: 'org-vanguard-fin',
    timestamp: '2026-09-01T21:05:44Z',
    source: 'VAN-TRADE-PROD01',
    sourceType: 'ENDPOINT_AGENT',
    severity: 'LOW',
    eventCategory: 'Authentication',
    sourceIP: '10.50.1.20',
    username: 'svc_quant_engine',
    host: 'VAN-TRADE-PROD01',
    eventDescription: 'Service account automated authentication rotation completed successfully.',
    rawEventReference: 'win_evt_id=4624 LogonType=5 TargetUserName="svc_quant_engine" Status=0x0',
    status: 'PROCESSED',
    createdTimestamp: '2026-09-01T21:05:45Z'
  }
];

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'alt-1049',
    organizationId: 'org-apex-logistics',
    title: 'Brute-Force Attack on SSL-VPN Perimeter Gateway',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    detectionRuleId: 'rule-brute-force',
    detectionRuleName: 'Excessive Failed Authentication Attempts (Brute-Force)',
    assetId: 'ast-apex-02',
    assetHostname: 'APEX-FW01-FORTIGATE',
    username: 'admin',
    timestamp: '2026-09-01T22:14:25Z',
    evidence: '14 failed login attempts from external IP 185.220.101.44 in 45 seconds targeting administrative credentials.',
    relatedEventIds: ['evt-8901'],
    recommendedAction: 'Verify firewall drop policy, block IP subnet at upstream provider, inspect if any successful session occurred.',
    assignedAnalystId: 'usr-stk-analyst-1',
    assignedAnalystName: 'Elena Rostova (SOC Tier 2)',
    linkedIncidentId: 'inc-apex-2026-01',
    analystNotes: [
      '2026-09-01 22:16Z: Elena Rostova - Validated IP is a known Tor exit node. Added IP to perimeter shunning group.',
      '2026-09-01 22:18Z: Elena Rostova - Checked authentication logs for succeeding tokens: none found. Elevating to incident INC-APEX-2026-01.'
    ],
    createdAt: '2026-09-01T22:14:25Z'
  },
  {
    id: 'alt-1050',
    organizationId: 'org-apex-logistics',
    title: 'Impossible Travel Anomaly: Account Compromise Suspected',
    severity: 'HIGH',
    status: 'NEW',
    detectionRuleId: 'rule-impossible-travel',
    detectionRuleName: 'Impossible Travel / Anomalous Geolocation',
    assetId: 'ast-apex-04',
    assetHostname: 'APEX-FIN-LT08',
    username: 'dsterling@apexlogistics.com',
    timestamp: '2026-09-01T22:15:15Z',
    evidence: 'Authentication from Chicago (IP 203.0.113.88) at 18:30Z followed by Sofia, Bulgaria (IP 45.154.255.90) at 22:15Z.',
    relatedEventIds: ['evt-8902'],
    recommendedAction: 'Immediately terminate active sessions, reset Microsoft 365 credentials, and request customer admin verification.',
    assignedAnalystId: 'usr-stk-analyst-1',
    assignedAnalystName: 'Elena Rostova (SOC Tier 2)',
    createdAt: '2026-09-01T22:15:15Z'
  },
  {
    id: 'alt-1051',
    organizationId: 'org-nexus-health',
    title: 'Endpoint Malware Neutralized: Qakbot Downloader Blocked',
    severity: 'HIGH',
    status: 'ACKNOWLEDGED',
    detectionRuleId: 'rule-malware-quarantine',
    detectionRuleName: 'Endpoint Malware Execution / Quarantine Trigger',
    assetId: 'ast-nexus-02',
    assetHostname: 'NEXUS-CLINIC-WS12',
    username: 'rn_station3',
    timestamp: '2026-09-01T19:10:05Z',
    evidence: 'Trojan:O97M/Qakbot.gen!pz detected in temp directory following email attachment preview. Quarantined.',
    relatedEventIds: ['evt-8905'],
    recommendedAction: 'Isolate workstation, verify email gateway sandbox rules, scan all workstations in clinic subnet.',
    assignedAnalystId: 'usr-stk-analyst-1',
    assignedAnalystName: 'Elena Rostova (SOC Tier 2)',
    analystNotes: [
      '2026-09-01 19:25Z: Elena Rostova - Workstation quarantined automatically by Defender. Running full offline signature scan.'
    ],
    createdAt: '2026-09-01T19:10:05Z'
  },
  {
    id: 'alt-1052',
    organizationId: 'org-apex-logistics',
    title: 'SSL/TLS Certificate Expiration Warning: *.apexlogistics.com',
    severity: 'MEDIUM',
    status: 'ACKNOWLEDGED',
    detectionRuleId: 'rule-cert-expiry-critical',
    detectionRuleName: 'SSL/TLS Certificate Expiration Imminent (< 7 Days)',
    assetId: 'ast-apex-02',
    assetHostname: 'APEX-FW01-FORTIGATE',
    timestamp: '2026-09-01T08:00:00Z',
    evidence: 'Wildcard certificate expires in 6 days (2026-09-07T23:59:59Z).',
    relatedEventIds: [],
    recommendedAction: 'Coordinate renewal with DigiCert registrar and deploy new CRT to FortiGate and Nginx reverse proxy.',
    assignedAnalystId: 'usr-stk-analyst-1',
    assignedAnalystName: 'Elena Rostova (SOC Tier 2)',
    createdAt: '2026-09-01T08:00:00Z'
  }
];

export const INITIAL_INCIDENTS: SecurityIncident[] = [
  {
    id: 'inc-apex-2026-01',
    organizationId: 'org-apex-logistics',
    title: 'Targeted Password Spray & Credential Stuffing on Perimeter Gateway',
    description: 'Coordinated credential stuffing attack originating from distributed Tor exit nodes against FortiGate SSL-VPN endpoint followed by impossible travel anomaly on executive user account.',
    severity: 'CRITICAL',
    status: 'CONTAINMENT',
    assignedAnalystId: 'usr-stk-analyst-1',
    assignedAnalystName: 'Elena Rostova (SOC Tier 2)',
    affectedAssetIds: ['ast-apex-02', 'ast-apex-04'],
    affectedAssetHostnames: ['APEX-FW01-FORTIGATE', 'APEX-FIN-LT08'],
    relatedAlertIds: ['alt-1049', 'alt-1050'],
    relatedEventIds: ['evt-8901', 'evt-8902'],
    timeline: [
      {
        id: 'tl-1',
        timestamp: '2026-09-01T22:14:22Z',
        actor: 'Detection Engine',
        action: 'Alert Generated',
        description: 'Excessive failed authentication threshold breached (14 attempts in 45s).',
        type: 'SYSTEM'
      },
      {
        id: 'tl-2',
        timestamp: '2026-09-01T22:16:40Z',
        actor: 'Elena Rostova (SOC)',
        action: 'Incident Declared',
        description: 'SOC Analyst elevated Alert ALT-1049 to Incident INC-APEX-2026-01. Notified customer emergency contact.',
        type: 'STATUS_CHANGE'
      },
      {
        id: 'tl-3',
        timestamp: '2026-09-01T22:18:10Z',
        actor: 'Elena Rostova (SOC)',
        action: 'Containment Action Executed',
        description: 'Blocked external IP subnet 185.220.101.0/24 on perimeter firewall. Revoked Microsoft 365 OAuth session tokens for dsterling@apexlogistics.com.',
        type: 'ANALYST_ACTION'
      },
      {
        id: 'tl-4',
        timestamp: '2026-09-01T22:25:00Z',
        actor: 'David Sterling (Customer Admin)',
        action: 'Credential Rotation Completed',
        description: 'Password reset and FIDO2 MFA re-registration completed with user.',
        type: 'ANALYST_ACTION'
      }
    ],
    evidence: [
      'Firewall auth log fg_log_id=0100032001 showing 14 failed logins from 185.220.101.44.',
      'Entra ID anomalous sign-in log from Sofia, BG using stolen legacy refresh token.',
      'Netflow telemetry showing 0 bytes exfiltrated after session revocation.'
    ],
    notes: [
      'Customer admin contacted via SMS hotline at 22:17Z. Confirmed executive is currently in Chicago and did not initiate Bulgarian login.',
      'Active threat actor blocked. Monitoring next 24 hours for follow-up attempts.'
    ],
    actionsTaken: [
      'Perimeter firewall IP blocking rule activated',
      'All active cloud sessions revoked for compromised principal',
      'Forced password change and hardware token MFA enrollment'
    ],
    resolution: undefined,
    rootCause: 'Leaked legacy credentials from external third-party data breach used in automated spray against single-factor VPN portal.',
    lessonsLearned: 'Mandate conditional access policy enforcing strict IP whitelisting and FIDO2 MFA for all external VPN portals.',
    createdAt: '2026-09-01T22:16:40Z',
    updatedAt: '2026-09-01T22:30:00Z'
  },
  {
    id: 'inc-nexus-2026-01',
    organizationId: 'org-nexus-health',
    title: 'Contained Phishing Attachment & Qakbot Dropper Execution',
    description: 'Clinic nurse workstation opened malicious weaponized invoice attachment. Endpoint EDR automatically intercepted and quarantined process before lateral movement.',
    severity: 'HIGH',
    status: 'ERADICATION',
    assignedAnalystId: 'usr-stk-analyst-1',
    assignedAnalystName: 'Elena Rostova (SOC Tier 2)',
    affectedAssetIds: ['ast-nexus-02'],
    affectedAssetHostnames: ['NEXUS-CLINIC-WS12'],
    relatedAlertIds: ['alt-1051'],
    relatedEventIds: ['evt-8905'],
    timeline: [
      {
        id: 'tl-n1',
        timestamp: '2026-09-01T19:10:05Z',
        actor: 'Detection Engine',
        action: 'Malware Alert Fired',
        description: 'EDR detected Trojan:O97M/Qakbot.gen!pz in temp directory.',
        type: 'SYSTEM'
      },
      {
        id: 'tl-n2',
        timestamp: '2026-09-01T19:15:00Z',
        actor: 'Elena Rostova (SOC)',
        action: 'Network Isolation',
        description: 'Endpoint NEXUS-CLINIC-WS12 isolated from healthcare internal subnet to prevent lateral movement.',
        type: 'ANALYST_ACTION'
      },
      {
        id: 'tl-n3',
        timestamp: '2026-09-01T19:40:00Z',
        actor: 'Elena Rostova (SOC)',
        action: 'Threat Eradication',
        description: 'Full malware artifact purge, temporary file deletion, and memory inspection completed.',
        type: 'ANALYST_ACTION'
      }
    ],
    evidence: [
      'Email message-id <202609011905.invoice_771@phish-delivery-net.org> with payload invoice_doc_771.vbs',
      'Defender log confirming process termination before any C2 beacon was established.'
    ],
    notes: [
      'HIPAA compliance officer notified. No ePHI was accessed or modified during the event.'
    ],
    actionsTaken: [
      'Host network isolated',
      'Malicious sender domain blocked in Microsoft 365 Exchange Online Protection',
      'Endpoint re-scanned and verified clean'
    ],
    createdAt: '2026-09-01T19:15:00Z',
    updatedAt: '2026-09-01T20:00:00Z'
  }
];

export const INITIAL_VULNERABILITIES: Vulnerability[] = [
  {
    id: 'vuln-01',
    organizationId: 'org-apex-logistics',
    cveId: 'CVE-2024-21762',
    title: 'FortiOS Out-of-Bound Write in SSL-VPN Web Portal',
    description: 'A out-of-bounds write vulnerability in Fortinet FortiOS may allow a remote unauthenticated attacker to execute arbitrary code or commands via specially crafted HTTP requests.',
    cvssScore: 9.8,
    severity: 'CRITICAL',
    affectedAssetId: 'ast-apex-02',
    affectedAssetHostname: 'APEX-FW01-FORTIGATE',
    software: 'FortiOS',
    installedVersion: '7.4.3 build2573',
    fixedVersion: '7.4.4',
    detectionDate: '2026-08-25',
    status: 'IN_PROGRESS',
    dueDate: '2026-09-05',
    assignedPerson: 'David Sterling (Customer Admin)',
    remediationGuidance: 'Upgrade FortiOS to version 7.4.4 or higher, or disable SSL-VPN web portal if unused.',
    patchAvailable: true,
    createdAt: '2026-08-25T10:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z'
  },
  {
    id: 'vuln-02',
    organizationId: 'org-apex-logistics',
    cveId: 'CVE-2024-3400',
    title: 'Command Injection in Palo Alto PAN-OS GlobalProtect (Adjacent Threat Audit)',
    description: 'Arbitrary command injection vulnerability allowing an unauthenticated attacker to execute arbitrary code with root privileges on the firewall.',
    cvssScore: 10.0,
    severity: 'CRITICAL',
    affectedAssetId: 'ast-apex-03',
    affectedAssetHostname: 'APEX-APP01-LNX',
    software: 'OpenSSL / Network Utilities',
    installedVersion: '3.0.2-0ubuntu1.14',
    fixedVersion: '3.0.2-0ubuntu1.15',
    detectionDate: '2026-08-28',
    status: 'OPEN',
    dueDate: '2026-09-10',
    assignedPerson: 'Elena Rostova (SOC)',
    remediationGuidance: 'Apply Ubuntu security package updates via apt-get upgrade.',
    patchAvailable: true,
    createdAt: '2026-08-28T14:00:00Z',
    updatedAt: '2026-08-28T14:00:00Z'
  },
  {
    id: 'vuln-03',
    organizationId: 'org-nexus-health',
    cveId: 'CVE-2023-4966',
    title: 'Citrix Bleed Sensitive Information Disclosure',
    description: 'Sensitive information disclosure vulnerability allowing session token theft from NetScaler Gateway memory buffer.',
    cvssScore: 9.4,
    severity: 'CRITICAL',
    affectedAssetId: 'ast-nexus-02',
    affectedAssetHostname: 'NEXUS-CLINIC-WS12',
    software: 'Citrix Workspace Client',
    installedVersion: '23.8.0',
    fixedVersion: '23.9.1',
    detectionDate: '2026-08-20',
    status: 'OPEN',
    dueDate: '2026-09-03',
    assignedPerson: 'Dr. Rachel Adams',
    remediationGuidance: 'Update Citrix Workspace App on all clinic workstation endpoints.',
    patchAvailable: true,
    createdAt: '2026-08-20T09:00:00Z',
    updatedAt: '2026-08-20T09:00:00Z'
  },
  {
    id: 'vuln-04',
    organizationId: 'org-vanguard-fin',
    cveId: 'CVE-2024-1709',
    title: 'ConnectWise ScreenConnect Authentication Bypass',
    description: 'Authentication bypass using an alternate path or channel in ConnectWise ScreenConnect.',
    cvssScore: 10.0,
    severity: 'CRITICAL',
    affectedAssetId: 'ast-van-01',
    affectedAssetHostname: 'VAN-TRADE-PROD01',
    software: 'Remote Management Agent',
    installedVersion: '23.9.7',
    fixedVersion: '23.9.8',
    detectionDate: '2026-08-15',
    status: 'REMEDIATED',
    dueDate: '2026-08-18',
    assignedPerson: 'Alexander Sterling',
    remediationGuidance: 'Remediated. Patched to 23.9.8 and verified no unauthorized admin accounts were spawned.',
    patchAvailable: true,
    createdAt: '2026-08-15T08:00:00Z',
    updatedAt: '2026-08-17T16:00:00Z'
  }
];

export const INITIAL_CERTIFICATES: SslCertificate[] = [
  {
    id: 'cert-apex-01',
    organizationId: 'org-apex-logistics',
    domain: '*.apexlogistics.com',
    issuer: 'DigiCert Global Root G2',
    validFrom: '2025-09-07T00:00:00Z',
    validUntil: '2026-09-07T23:59:59Z',
    daysRemaining: 6,
    status: 'EXPIRING_SOON',
    tlsVersion: 'TLS 1.3 / TLS 1.2',
    chainStatus: 'VALID',
    keySize: 'RSA 2048-bit',
    lastChecked: '2026-09-01T22:00:00Z'
  },
  {
    id: 'cert-apex-02',
    organizationId: 'org-apex-logistics',
    domain: 'portal.apexlogistics.com',
    issuer: "Let's Encrypt Authority X3",
    validFrom: '2026-07-15T00:00:00Z',
    validUntil: '2026-10-15T23:59:59Z',
    daysRemaining: 44,
    status: 'VALID',
    tlsVersion: 'TLS 1.3',
    chainStatus: 'VALID',
    keySize: 'ECDSA 256-bit',
    lastChecked: '2026-09-01T22:00:00Z'
  },
  {
    id: 'cert-nexus-01',
    organizationId: 'org-nexus-health',
    domain: 'ehr-portal.nexushealth.org',
    issuer: 'Sectigo RSA Extended Validation CA',
    validFrom: '2026-01-10T00:00:00Z',
    validUntil: '2027-01-10T23:59:59Z',
    daysRemaining: 131,
    status: 'VALID',
    tlsVersion: 'TLS 1.3',
    chainStatus: 'VALID',
    keySize: 'RSA 4096-bit',
    lastChecked: '2026-09-01T22:00:00Z'
  },
  {
    id: 'cert-van-01',
    organizationId: 'org-vanguard-fin',
    domain: 'secure-trade.vanguardfin.com',
    issuer: 'Entrust Global Root Certification Authority',
    validFrom: '2026-03-01T00:00:00Z',
    validUntil: '2027-03-01T23:59:59Z',
    daysRemaining: 181,
    status: 'VALID',
    tlsVersion: 'TLS 1.3',
    chainStatus: 'VALID',
    keySize: 'ECDSA 384-bit',
    lastChecked: '2026-09-01T22:00:00Z'
  }
];

export const INITIAL_DOMAINS: MonitoredDomain[] = [
  {
    id: 'dom-apex-01',
    organizationId: 'org-apex-logistics',
    domainName: 'apexlogistics.com',
    registrar: 'GoDaddy Inc.',
    expirationDate: '2026-11-20T00:00:00Z',
    daysToExpiry: 80,
    dnsAvailability: true,
    nameservers: ['ns1.apexlogistics.com', 'ns2.apexlogistics.com'],
    mxRecords: ['10 apexlogistics-com.mail.protection.outlook.com'],
    spfRecord: 'v=spf1 include:spf.protection.outlook.com -all',
    spfValid: true,
    dmarcRecord: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@apexlogistics.com; pct=100',
    dmarcValid: true,
    dkimConfigured: true,
    dnssecEnabled: false,
    lastChecked: '2026-09-01T21:00:00Z'
  },
  {
    id: 'dom-nexus-01',
    organizationId: 'org-nexus-health',
    domainName: 'nexushealth.org',
    registrar: 'Network Solutions',
    expirationDate: '2027-05-15T00:00:00Z',
    daysToExpiry: 256,
    dnsAvailability: true,
    nameservers: ['ns1.cloudflare.com', 'ns2.cloudflare.com'],
    mxRecords: ['1 aspmx.l.google.com', '5 alt1.aspmx.l.google.com'],
    spfRecord: 'v=spf1 include:_spf.google.com ~all',
    spfValid: true,
    dmarcRecord: 'v=DMARC1; p=reject; rua=mailto:dmarc-reports@nexushealth.org',
    dmarcValid: true,
    dkimConfigured: true,
    dnssecEnabled: true,
    lastChecked: '2026-09-01T21:30:00Z'
  },
  {
    id: 'dom-van-01',
    organizationId: 'org-vanguard-fin',
    domainName: 'vanguardfin.com',
    registrar: 'MarkMonitor Inc.',
    expirationDate: '2028-02-01T00:00:00Z',
    daysToExpiry: 518,
    dnsAvailability: true,
    nameservers: ['ns-101.awsdns-12.com', 'ns-800.awsdns-36.net'],
    mxRecords: ['0 mail.vanguardfin.com'],
    spfRecord: 'v=spf1 ip4:198.51.100.0/24 -all',
    spfValid: true,
    dmarcRecord: 'v=DMARC1; p=reject; sp=reject; adkim=s; aspf=s',
    dmarcValid: true,
    dkimConfigured: true,
    dnssecEnabled: true,
    lastChecked: '2026-09-01T21:45:00Z'
  }
];

export const INITIAL_BACKUPS: BackupRecord[] = [
  {
    id: 'bkp-apex-01',
    organizationId: 'org-apex-logistics',
    backupSystem: 'Veeam Backup & Replication v12',
    protectedAssetId: 'ast-apex-01',
    protectedAssetName: 'APEX-DC01-WIN (Active Directory DC)',
    lastSuccessfulBackup: '2026-09-01T02:00:00Z',
    backupAgeHours: 20,
    status: 'SUCCESS',
    recoveryPointStatus: 'RPO_MET',
    backupSizeBytes: 42949672960, // 40 GB
    destination: 'Immutable S3 Wasabi Bucket (Chicago-Vault-01)',
    lastChecked: '2026-09-01T22:00:00Z'
  },
  {
    id: 'bkp-apex-02',
    organizationId: 'org-apex-logistics',
    backupSystem: 'Veeam Backup & Replication v12',
    protectedAssetId: 'ast-apex-03',
    protectedAssetName: 'APEX-APP01-LNX (Dispatch VM)',
    lastSuccessfulBackup: '2026-08-30T03:00:00Z',
    lastFailedBackup: '2026-09-01T03:00:00Z',
    backupAgeHours: 43,
    status: 'FAILED',
    recoveryPointStatus: 'RPO_BREACHED',
    backupSizeBytes: 128849018880, // 120 GB
    destination: 'Local QNAP NAS Storage (Pool-B)',
    lastChecked: '2026-09-01T22:00:00Z'
  },
  {
    id: 'bkp-nexus-01',
    organizationId: 'org-nexus-health',
    backupSystem: 'AWS Backup / PostgreSQL Snapshot',
    protectedAssetId: 'ast-nexus-01',
    protectedAssetName: 'NEXUS-EHR-DB01 (Clinical Database)',
    lastSuccessfulBackup: '2026-09-01T18:00:00Z',
    backupAgeHours: 4,
    status: 'SUCCESS',
    recoveryPointStatus: 'RPO_MET',
    backupSizeBytes: 536870912000, // 500 GB
    destination: 'AWS KMS Encrypted Vault (us-east-1 HIPAA Compliant)',
    lastChecked: '2026-09-01T22:15:00Z'
  },
  {
    id: 'bkp-van-01',
    organizationId: 'org-vanguard-fin',
    backupSystem: 'Commvault Complete Data Protection',
    protectedAssetId: 'ast-van-01',
    protectedAssetName: 'VAN-TRADE-PROD01 (Trading Core)',
    lastSuccessfulBackup: '2026-09-01T21:00:00Z',
    backupAgeHours: 1,
    status: 'SUCCESS',
    recoveryPointStatus: 'RPO_MET',
    backupSizeBytes: 1073741824000, // 1 TB
    destination: 'Air-Gapped WORM Optical Array + Azure Archive',
    lastChecked: '2026-09-01T22:30:00Z'
  }
];

export const INITIAL_EXTERNAL_EXPOSURE: ExternalExposureRecord[] = [
  {
    id: 'exp-apex-01',
    organizationId: 'org-apex-logistics',
    target: 'apexlogistics.com / 198.51.100.254',
    publicIp: '198.51.100.254',
    openPorts: [80, 443, 10443],
    discoveredServices: ['nginx/1.24.0 (HTTP)', 'OpenSSL/3.0.2 (HTTPS)', 'Fortinet SSL-VPN Gateway'],
    httpSecurityHeaders: {
      hsts: true,
      csp: false,
      xFrameOptions: true,
      xContentTypeOptions: true
    },
    threatExposureGrade: 'C',
    lastScanned: '2026-09-01T12:00:00Z'
  },
  {
    id: 'exp-nexus-01',
    organizationId: 'org-nexus-health',
    target: 'ehr-portal.nexushealth.org / 198.18.0.1',
    publicIp: '198.18.0.1',
    openPorts: [443],
    discoveredServices: ['Cloudflare Enterprise Edge (HTTPS)'],
    httpSecurityHeaders: {
      hsts: true,
      csp: true,
      xFrameOptions: true,
      xContentTypeOptions: true
    },
    threatExposureGrade: 'A',
    lastScanned: '2026-09-01T14:30:00Z'
  },
  {
    id: 'exp-van-01',
    organizationId: 'org-vanguard-fin',
    target: 'secure-trade.vanguardfin.com / 198.51.100.99',
    publicIp: '198.51.100.99',
    openPorts: [443, 8443],
    discoveredServices: ['Akamai Kona Site Defender (mTLS Required)'],
    httpSecurityHeaders: {
      hsts: true,
      csp: true,
      xFrameOptions: true,
      xContentTypeOptions: true
    },
    threatExposureGrade: 'A',
    lastScanned: '2026-09-01T16:00:00Z'
  }
];

export const INITIAL_IDENTITY_STATS: IdentityAuthStat[] = [
  {
    id: 'id-apex-01',
    organizationId: 'org-apex-logistics',
    timeRange: 'Last 24 Hours',
    totalLoginAttempts: 412,
    failedLogins: 28,
    accountLockouts: 2,
    mfaCoveragePercent: 78,
    suspiciousGeographyCount: 4,
    impossibleTravelEvents: 1,
    privilegeEscalations: 0,
    newAdminsCreated: 0
  },
  {
    id: 'id-nexus-01',
    organizationId: 'org-nexus-health',
    timeRange: 'Last 24 Hours',
    totalLoginAttempts: 680,
    failedLogins: 12,
    accountLockouts: 0,
    mfaCoveragePercent: 94,
    suspiciousGeographyCount: 1,
    impossibleTravelEvents: 0,
    privilegeEscalations: 0,
    newAdminsCreated: 0
  },
  {
    id: 'id-van-01',
    organizationId: 'org-vanguard-fin',
    timeRange: 'Last 24 Hours',
    totalLoginAttempts: 920,
    failedLogins: 5,
    accountLockouts: 0,
    mfaCoveragePercent: 100,
    suspiciousGeographyCount: 0,
    impossibleTravelEvents: 0,
    privilegeEscalations: 0,
    newAdminsCreated: 0
  }
];

export const INITIAL_THREAT_INTEL: ThreatIntelligenceIndicator[] = [
  {
    id: 'ioc-01',
    indicator: '185.220.101.44',
    type: 'IP',
    source: 'AbuseIPDB & PNGee Global Threat Feed',
    confidence: 96,
    reputation: 'MALICIOUS',
    threatGroup: 'UNC4841 (Reconnaissance Cluster)',
    malwareFamily: 'Tor Password Spray Botnet',
    firstSeen: '2026-08-01T00:00:00Z',
    lastSeen: '2026-09-01T22:14:00Z',
    expiresAt: '2026-10-01T00:00:00Z'
  },
  {
    id: 'ioc-02',
    indicator: '45.154.255.90',
    type: 'IP',
    source: 'CrowdStrike Falcon Intelligence',
    confidence: 90,
    reputation: 'SUSPICIOUS',
    threatGroup: 'Scattered Spider Proxy Pool',
    firstSeen: '2026-08-20T10:00:00Z',
    lastSeen: '2026-09-01T22:15:00Z',
    expiresAt: '2026-09-20T00:00:00Z'
  },
  {
    id: 'ioc-03',
    indicator: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    type: 'FILE_HASH_SHA256',
    source: 'Mandiant Threat Library',
    confidence: 99,
    reputation: 'MALICIOUS',
    threatGroup: 'BlackCat / ALPHV',
    malwareFamily: 'Qakbot Loader v4',
    firstSeen: '2026-07-15T00:00:00Z',
    lastSeen: '2026-09-01T19:10:00Z',
    expiresAt: '2027-01-01T00:00:00Z'
  },
  {
    id: 'ioc-04',
    indicator: 'phish-delivery-net.org',
    type: 'DOMAIN',
    source: 'URLhaus / Spamhaus',
    confidence: 95,
    reputation: 'MALICIOUS',
    threatGroup: 'TA577 Phishing Campaign',
    firstSeen: '2026-08-29T00:00:00Z',
    lastSeen: '2026-09-01T19:05:00Z',
    expiresAt: '2026-11-29T00:00:00Z'
  }
];

export const INITIAL_INTEGRATIONS: IntegrationConnector[] = [
  {
    id: 'int-01',
    name: 'Fortinet FortiGate Firewall Syslog & API Connector',
    vendor: 'Fortinet',
    category: 'FIREWALL',
    status: 'CONNECTED',
    organizationId: 'org-apex-logistics',
    lastSyncAt: '2026-09-01T22:42:00Z',
    eventsIngested24h: 18420
  },
  {
    id: 'int-02',
    name: 'Microsoft 365 / Entra ID Audit Log Streaming',
    vendor: 'Microsoft 365',
    category: 'IDENTITY',
    status: 'CONNECTED',
    organizationId: 'org-apex-logistics',
    lastSyncAt: '2026-09-01T22:40:00Z',
    eventsIngested24h: 3950
  },
  {
    id: 'int-03',
    name: 'pfSense Suricata IPS / Firewall Ingestion',
    vendor: 'pfSense',
    category: 'FIREWALL',
    status: 'CONNECTED',
    organizationId: 'org-nexus-health',
    lastSyncAt: '2026-09-01T22:38:00Z',
    eventsIngested24h: 12100
  },
  {
    id: 'int-04',
    name: 'CrowdStrike Falcon EDR API Bridge',
    vendor: 'CrowdStrike',
    category: 'ENDPOINT_EDR',
    status: 'CONNECTED',
    organizationId: 'org-vanguard-fin',
    lastSyncAt: '2026-09-01T22:41:00Z',
    eventsIngested24h: 24800
  },
  {
    id: 'int-05',
    name: 'AWS CloudTrail & GuardDuty EventBridge Connector',
    vendor: 'AWS CloudTrail',
    category: 'CLOUD',
    status: 'CONNECTED',
    organizationId: 'org-nexus-health',
    lastSyncAt: '2026-09-01T22:35:00Z',
    eventsIngested24h: 8400
  },
  {
    id: 'int-06',
    name: 'Cisco Meraki & Catalyst Switch Connector',
    vendor: 'Cisco',
    category: 'SIEM_SYSLOG',
    status: 'AVAILABLE',
    eventsIngested24h: 0
  },
  {
    id: 'int-07',
    name: 'Ubiquiti UniFi Gateway & AP Telemetry',
    vendor: 'Ubiquiti',
    category: 'SIEM_SYSLOG',
    status: 'AVAILABLE',
    eventsIngested24h: 0
  },
  {
    id: 'int-08',
    name: 'Google Workspace Enterprise Security Audit Ingest',
    vendor: 'Google Workspace',
    category: 'IDENTITY',
    status: 'AVAILABLE',
    eventsIngested24h: 0
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-101',
    timestamp: '2026-09-01T22:18:10Z',
    actor: 'Elena Rostova',
    actorEmail: 'analyst@stkcyberguard.com',
    organizationId: 'org-apex-logistics',
    organizationName: 'Apex Global Logistics Inc.',
    action: 'INCIDENT_ACTION_EXECUTED',
    resource: 'Incident',
    resourceId: 'inc-apex-2026-01',
    sourceIP: '198.51.100.12',
    result: 'SUCCESS',
    details: { action: 'Blocked IP 185.220.101.44 on FortiGate perimeter' }
  },
  {
    id: 'aud-102',
    timestamp: '2026-09-01T22:16:40Z',
    actor: 'Elena Rostova',
    actorEmail: 'analyst@stkcyberguard.com',
    organizationId: 'org-apex-logistics',
    organizationName: 'Apex Global Logistics Inc.',
    action: 'INCIDENT_CREATED',
    resource: 'Incident',
    resourceId: 'inc-apex-2026-01',
    sourceIP: '198.51.100.12',
    result: 'SUCCESS',
    details: { severity: 'CRITICAL', title: 'Targeted Password Spray & Credential Stuffing' }
  },
  {
    id: 'aud-103',
    timestamp: '2026-09-01T21:45:00Z',
    actor: 'Marcus Vance',
    actorEmail: 'admin@pngeecyberguard.com',
    organizationId: 'org-pngee-global',
    organizationName: 'PNGee IT Solutions (Global SOC & Operations)',
    action: 'USER_LOGIN',
    resource: 'Auth',
    resourceId: 'usr-pngee-admin-1',
    sourceIP: '198.51.100.4',
    result: 'SUCCESS',
    details: { method: 'MFA_FIDO2' }
  },
  {
    id: 'aud-104',
    timestamp: '2026-09-01T19:15:00Z',
    actor: 'Elena Rostova',
    actorEmail: 'analyst@pngeecyberguard.com',
    organizationId: 'org-nexus-health',
    organizationName: 'Nexus Healthcare Systems LLC',
    action: 'HOST_NETWORK_ISOLATED',
    resource: 'Asset',
    resourceId: 'ast-nexus-02',
    sourceIP: '198.51.100.12',
    result: 'SUCCESS',
    details: { reason: 'Quarantined Qakbot malware execution' }
  }
];

export const INITIAL_NOTIFICATION_RULES: NotificationRule[] = [
  {
    id: 'notif-apex-01',
    organizationId: 'org-apex-logistics',
    name: 'Apex 24/7 Critical Threat PagerDuty & Email',
    enabled: true,
    channels: ['EMAIL', 'IN_APP', 'WEBHOOK'],
    minSeverity: 'HIGH',
    eventCategories: ['Authentication', 'Malware', 'Identity', 'Firewall'],
    recipients: ['it-security@apexlogistics.com', 'soc-escalations@pngeecyberguard.com'],
    webhookUrl: 'https://events.pagerduty.com/v2/enqueue',
    businessHoursOnly: false
  },
  {
    id: 'notif-nexus-01',
    organizationId: 'org-nexus-health',
    name: 'Nexus Healthcare Compliance Emergency Pager',
    enabled: true,
    channels: ['EMAIL', 'IN_APP'],
    minSeverity: 'HIGH',
    eventCategories: ['Authentication', 'Malware', 'Data security', 'Vulnerability'],
    recipients: ['compliance@nexushealth.org', 'ciso-oncall@nexushealth.org'],
    businessHoursOnly: false
  }
];

export const INITIAL_ENROLLMENT_TOKENS: AgentEnrollmentToken[] = [
  {
    id: 'tok-apex-01',
    organizationId: 'org-apex-logistics',
    tokenKey: 'pngee_agent_apex_win_prod_99f82a10b47e',
    name: 'Apex HQ Windows Rollout Token (GPO)',
    osTarget: 'windows',
    createdBy: 'David Sterling',
    expiresAt: '2026-12-31T23:59:59Z',
    isRevoked: false,
    usedCount: 22,
    maxUses: 100,
    createdAt: '2025-03-15T00:00:00Z'
  },
  {
    id: 'tok-nexus-01',
    organizationId: 'org-nexus-health',
    tokenKey: 'pngee_agent_nexus_clinic_sec_8812ab44',
    name: 'Nexus Clinical Workstation Token',
    osTarget: 'all',
    createdBy: 'Dr. Rachel Adams',
    expiresAt: '2026-12-31T23:59:59Z',
    isRevoked: false,
    usedCount: 16,
    maxUses: 50,
    createdAt: '2025-05-25T00:00:00Z'
  }
];

export const INITIAL_REPORTS: SecurityReport[] = [
  {
    id: 'rep-apex-aug2026',
    organizationId: 'org-apex-logistics',
    organizationName: 'Apex Global Logistics Inc.',
    reportType: 'EXECUTIVE',
    title: 'Monthly Executive Cybersecurity Posture Review — August 2026',
    dateRange: { start: '2026-08-01', end: '2026-08-31' },
    generatedBy: 'Marcus Vance (PNGee Lead)',
    generatedAt: '2026-09-01T08:00:00Z',
    executiveSummary: 'During August 2026, PNGee CyberGuard protected Apex Global Logistics across 24 monitored assets, intercepting 3 perimeter attack bursts and preventing 1 lateral infection attempt. The overall security score improved from 74 to 81 (+7 pts), with key remediation completed on active directory backup immutability.',
    securityScore: 81,
    incidentsSummary: { total: 2, critical: 1, resolved: 2 },
    vulnerabilitiesSummary: { total: 6, critical: 2, remediated: 4 },
    endpointHealthSummary: { total: 24, online: 22, securePercent: 91 },
    backupHealthSummary: { total: 4, failingCount: 1 },
    topRecommendations: [
      'Upgrade FortiGate perimeter gateway to FortiOS 7.4.4 to patch critical CVE-2024-21762.',
      'Renew wildcard SSL certificate *.apexlogistics.com expiring in under 7 days.',
      'Enforce FIDO2 hardware MFA for all Microsoft 365 remote users.'
    ],
    status: 'READY'
  }
];
